# Generated by Django 6.0.2 on 2026-02-17 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("displayName", models.CharField(max_length=100)),
                ("github", models.URLField(blank=True)),
                ("profileImage", models.URLField(blank=True)),
                ("host", models.URLField()),
                ("url", models.URLField(unique=True)),
            ],
        ),
    ]
