# Generated by Django 6.0.2 on 2026-02-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="url",
            field=models.URLField(blank=True, unique=True),
        ),
    ]
