# Generated by Django 6.0.2 on 2026-02-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_author_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="displayName",
            field=models.CharField(max_length=225),
        ),
    ]
