# Generated by Django 6.0.2 on 2026-02-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_alter_author_displayname"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="url",
            field=models.URLField(blank=True, editable=False, unique=True),
        ),
    ]
