# Generated by Django 6.0.2 on 2026-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0007_author_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("UNLISTED", "Unlisted"),
                    ("FRIENDS", "Only Friends"),
                ],
                default="PUBLIC",
                max_length=8,
            ),
        ),
    ]
