# Generated by Django 6.0.2 on 2026-02-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_post_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMarkPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authors.post')),
                ('contenta', models.TextField()),
            ],
            bases=('authors.post',),
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authors.post')),
                ('contenta', models.ImageField(upload_to='')),
            ],
            bases=('authors.post',),
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authors.post')),
                ('contenta', models.TextField()),
            ],
            bases=('authors.post',),
        ),
    ]
