# Generated by Django 6.0.2 on 2026-02-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_commonmarkpost_imagepost_textpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='textpost',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='CommonMarkPost',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='TextPost',
        ),
    ]
