# Generated by Django 6.0.2 on 2026-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_remove_imagepost_post_ptr_remove_textpost_post_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('COMMONMARK', 'CommonMark'), ('IMAGE', 'Image')], default='TEXT'),
        ),
    ]
