# Generated by Django 6.0.2 on 2026-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_post_img_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_content_type',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
