# Generated by Django 6.0.2 on 2026-02-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_alter_post_img_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_content_type',
            new_name='content_type',
        ),
    ]
