# Generated by Django 6.0.2 on 2026-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_alter_author_followers_alter_author_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
