# Generated by Django 6.0.1 on 2026-02-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_alter_author_followers_alter_author_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField()),
                ('contentType', models.CharField(default='text/plain', max_length=50)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends-Only'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('object', models.URLField(db_index=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
