# Generated by Django 6.0.2 on 2026-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_author_api_url_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='api_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
