# Generated by Django 6.0.2 on 2026-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_alter_author_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='api_url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, to='authors.author'),
        ),
    ]
