# Generated by Django 6.0.2 on 2026-03-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_alter_author_github_alter_author_profileimage_entry_and_more'),
        ('authors', '0020_post_api_url_post_url_alter_author_followers_and_more'),
    ]

    operations = [
    ]
