# Generated by Django 6.0.2 on 2026-03-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0023_like_post_alter_like_id_comment_like_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, editable=False, unique=True),
        ),
    ]
