# Generated by Django 6.0.2 on 2026-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0024_like_object_alter_author_github_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'object')},
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
