# Generated by Django 6.0.2 on 2026-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0025_alter_like_unique_together_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=20),
        ),
    ]
