# Generated by Django 6.0.2 on 2026-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0029_alter_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='like',
            name='api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='like',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
