# Generated by Django 6.0.2 on 2026-03-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0032_populate_like_comment_url_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='api_url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='api_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
