# Generated by Django 6.0.2 on 2026-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0033_alter_comment_api_url_alter_like_api_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
