# Generated by Django 6.0.2 on 2026-03-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0037_alter_entry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(db_column='content_type', max_length=18, null=True),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'comment')},
        ),
        migrations.AddField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='authors.entry'),
        ),
        migrations.AddField(
            model_name='post',
            name='sent_to_nodes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(db_column='content_type', default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contentType',
            field=models.CharField(db_column='content_type', default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='like',
            name='api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Only Friends'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'comment'), ('author', 'entry')},
        ),
    ]
