# Generated by Django 6.0.2 on 2026-03-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0038_alter_post_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sent_to_nodes',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(related_name='sent_to', to='authors.post'),
        ),
    ]
