# Generated by Django 6.0.2 on 2026-03-22 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0039_remove_post_sent_to_nodes_alter_inbox_posts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'comment'), ('author', 'post')},
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='like',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object',
        ),
    ]
