# Generated by Django 6.0.2 on 2026-03-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0042_alter_node_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
