# Generated by Django 6.0.2 on 2026-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0043_alter_node_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
