# Generated by Django 6.0.2 on 2026-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_content_type',
            field=models.CharField(default='image/jpg;base64', max_length=18),
            preserve_default=False,
        ),
    ]
