# Generated by Django 6.0.2 on 2026-02-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_rename_img_content_type_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='authors.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(to='authors.author'),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('incoming_follow_requests', models.ManyToManyField(related_name='outgoing_follow_requests', to='authors.author')),
                ('posts', models.ManyToManyField(to='authors.post')),
            ],
        ),
    ]
