# Generated by Django 6.0.2 on 2026-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_alter_author_followers_alter_author_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='authors.author'),
        ),
    ]
